title: Sebastian DeLorenzo
email: sebastian.hn.delorenzo@gmail.com
description: C++ developer with an interest in Physics and History.
baseurl: "/home"
url: "https://sebastianhndelorenzo.github.io/"
github_username: sebastianhndelorenzo

theme: jekyll-theme-minimal
